function getImage(imagename) {
  return require(`../assets/${imagename}.svg`)
}

export const sdslabslogo = getImage('sdslabs-logo')
export const fblogo = getImage('fb-logo')
export const twitterlogo = getImage('twitter-logo')
export const githublogo=getImage('github-logo')
export const ctflogo=getImage('ctf-logo')
export const dropdown=getImage('dropdown')
export const edit=getImage('edit')
export const purge=getImage('purge')
export const play=getImage('play')
export const undeploy=getImage('undeploy')
export const add=getImage('add')
export const preview=getImage('preview')
export const upload=getImage('upload')
export const leaderboard=getImage('leaderboard')
export const search=getImage('search')
export const notifAdded=getImage('notif-added')
export const notifFailed=getImage('notif-failed')
export const mail=getImage('mail')
export const ban=getImage('ban')
export const unban=getImage('unban')
export const userPanel=getImage('userPanel')
